### ISSUE TITLE
Envoy graceful shutdown

### ISSUE THREAD

**Issue by stevesloka** [heptio/gimbal#144]
**Feature Request**

When restarting Envoy (i.e. upgrading, draining nodes, etc), the pod receives a SIGTERM from Kubernetes and all connections are dropped. We should signal to Envoy that it's going down and attempt to drain before rolling the pod: envoyproxy/envoy#1990 (comment)

We should be able to use the lifecycle hooks and add something like this, however, `curl` isn't in the envoy pod. So either we will need to add that which has our users utilize a custom image (not favorable), or we add another side-car which listens for the `SIGTERM` and sends the `POST` request to Envoy to shut down. 

```
lifecycle:
  preStop:
  exec:
    command: ["curl","-XPOST","http://localhost:9001/healthcheck/fail"] 
```

// #135

**Comment by rosskukulinski** [comment]
-1 to custom envoy image

**Comment by phylake** [comment]
No `curl` but you do have `wget`

**Comment by stevesloka** [comment]
We have this fixed in Contour (https://github.com/heptio/contour/pull/781). I'll leave this open so that we can update the examples in Gimbal to reflect.

**Comment by azuretek** [comment]
There's still an issue https://github.com/heptio/contour/pull/781#pullrequestreview-216314066

**Comment by davecheney** [comment]
@steveslola can you please take this one. Thank you.
